# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_group', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'products',
                'verbose_name': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imei', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'product instances',
                'verbose_name': 'product instance',
            },
        ),
    ]
