# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='000-000', max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('birthday', models.DateField(null=True)),
                ('promotion_code', models.CharField(max_length=100, null=True)),
                ('is_serviced', models.BooleanField(default=False)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'ordering': ['updated_at'],
                'verbose_name_plural': 'customers',
                'verbose_name': 'customer',
            },
        ),
    ]
