# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='000-000', max_length=20, null=True),
        ),
    ]
