# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['updated_at'], 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
