# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170323_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
